### ISSUE TITLE
How to use a different particle proposal?

### ISSUE THREAD

**Issue by Gabriel-p** [jakeret/abcpmc#17]
I'd like to try the `OLCMParticleProposal()` class, but it's not clear to me how to implement it. I looked around but couldn't find any examples of this.

Could you please add one?

**Comment by jakeret** [comment]
There is an example on how to use different particle proposal algorithm in one of the [demo notebooks](https://nbviewer.jupyter.org/github/jakeret/abcpmc/blob/master/notebooks/2d_gauss.ipynb). You find the relevant information in cell 12.
Does this help?

**Comment by Gabriel-p** [comment]
Sorry, I missed that line. Thank you!
